package cars.mybatis.dao;

import cars.mybatis.model.Carpart;
import java.util.List;

public interface CarpartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int insert(Carpart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    Carpart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    List<Carpart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int updateByPrimaryKey(Carpart record);
}