package cars.mybatis.dao;

import cars.mybatis.model.CarPart;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CarPartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int insert(CarPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    CarPart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    List<CarPart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int updateByPrimaryKey(CarPart record);

    List<CarPart> getSelectedCarParts(Integer modelId);
}