package cars.mybatis.dao;

import cars.mybatis.model.Manufacturer;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ManufacturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int insert(Manufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    Manufacturer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    List<Manufacturer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANUFACTURER
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int updateByPrimaryKey(Manufacturer record);
}