package cars.mybatis.dao;

import cars.mybatis.model.ModelCarPart;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ModelCarPartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL_CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int insert(ModelCarPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL_CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    List<ModelCarPart> selectAll();
}