package cars.mybatis.dao;

import cars.mybatis.model.ModelCarpart;
import java.util.List;

public interface ModelCarpartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL_CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    int insert(ModelCarpart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODEL_CARPART
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    List<ModelCarpart> selectAll();
}