package cars.mybatis.model;

public class Model {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.NAME
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.MANUFACTURER_ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    private Integer manufacturerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.ID
     *
     * @return the value of PUBLIC.MODEL.ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.ID
     *
     * @param id the value for PUBLIC.MODEL.ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.NAME
     *
     * @return the value of PUBLIC.MODEL.NAME
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.NAME
     *
     * @param name the value for PUBLIC.MODEL.NAME
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.MANUFACTURER_ID
     *
     * @return the value of PUBLIC.MODEL.MANUFACTURER_ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public Integer getManufacturerId() {
        return manufacturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.MANUFACTURER_ID
     *
     * @param manufacturerId the value for PUBLIC.MODEL.MANUFACTURER_ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public void setManufacturerId(Integer manufacturerId) {
        this.manufacturerId = manufacturerId;
    }
}