package cars.mybatis.model;

public class ModelCarpart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL_CARPART.MODELS_ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    private Integer modelsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL_CARPART.CARPARTS_ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    private Integer carpartsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL_CARPART.MODELS_ID
     *
     * @return the value of PUBLIC.MODEL_CARPART.MODELS_ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public Integer getModelsId() {
        return modelsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL_CARPART.MODELS_ID
     *
     * @param modelsId the value for PUBLIC.MODEL_CARPART.MODELS_ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public void setModelsId(Integer modelsId) {
        this.modelsId = modelsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL_CARPART.CARPARTS_ID
     *
     * @return the value of PUBLIC.MODEL_CARPART.CARPARTS_ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public Integer getCarpartsId() {
        return carpartsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL_CARPART.CARPARTS_ID
     *
     * @param carpartsId the value for PUBLIC.MODEL_CARPART.CARPARTS_ID
     *
     * @mbg.generated Tue May 12 00:09:55 EEST 2020
     */
    public void setCarpartsId(Integer carpartsId) {
        this.carpartsId = carpartsId;
    }
}